# Generated by Django 4.2.26 on 2025-11-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fire_school', 'Fire School'), ('water_school', 'Water School'), ('air_school', 'Air School')], max_length=20, unique=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sphere', 'Sphere'), ('pellets', 'Pellets')], max_length=20, unique=True)),
                ('icon', models.CharField(default='💫', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('enemy', 'Enemy Target'), ('spot', 'Ground Spot'), ('caster', 'Self (Caster)')], max_length=20, unique=True)),
                ('icon', models.CharField(default='🎯', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magic_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spells', to='spells.magicschool')),
                ('projectile_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spells', to='spells.projectileform')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spells', to='spells.targettype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
